### ISSUE TITLE
find() should return empty array

### ISSUE THREAD

**Issue by LorenzV** [ikkez/f3-cortex#12]
Hi,

I think find() should return an empty array. Doesn't the default Mapper find() do that?

For me it's also easier todo things like:

$users = $umodel->find(...);
foreach($users ...

Instead of:

$users = $umodel->find(...);
if(!$users) $users = array();
foreach($users ...

or... Is there a way to do a foreach on the result of load() ?

-------- EDIT:

Is this how you do it? (it works though)

$users = $umodel->load(...);
while(!$users->dry()){
     echo $users->id;
     $users->next();
}

**Comment by ikkez** [comment]
Well, probably yes, but on the other hand it would cause some more trouble, because actually it's not an array that is returned, but an instance of a CortexCollection. This implements ArrayIterator so you can use `foreach` to loop through all found records. If nothing is found but an empty CortexCollection is returned, then `if ($users)` would still be true, because it casts to an existing object, thus its true even if nothing was found. That would probably casue more false positives in your busicess code, so I think it's better to add a strict check if a result was given or not. That's less harmful.

**Comment by olaulau** [comment]
this is a big problem when using findone() on data that doesn't exist, as the cursor class of F3 is like that :
`return ($data=$this->find($filter,$options,$ttl))?$data[0]:FALSE;`
so if find doesn't return an empty array in this case, we have an error : `Undefined array key 0`
