### ISSUE TITLE
Q: Pivot table with 3 relations?

### ISSUE THREAD

**Issue by webbird** [ikkez/f3-cortex#15]
I have another question. I need a pivot table having 3 related tables. The tables are:

blocks
elements
templates

An element HAS a template ON a specific block. The same element may have a different template on a different block.

Can cortex handle this? (Of course I can maintain that special table outside the model if I have to.)

Thanks in advance.

**Comment by webbird** [comment]
Well, I found that I don't need this relations... However, I think it's still interesting to know, so if you don't mind... :)

**Comment by webbird** [comment]
Similar question: Can a pivot table have additional columns? Example: page HAS blocks ON position X.

Pivot table structure would be
    | id | page | blocks | position |

**Comment by ikkez** [comment]
Well, of course you can add those fields to the pivot table manually, but having multiple relations and extra fields in that table looks like you rather need another model instead of a simple pivot table. Cortex does not support meta data in pivot tables yet, but all use cases I have seen so far, could be solved with an extra model in between. Just create a new model (maybe named "content"), containing the page, block and template relation (all belongs-to-one types and has-many at the counterpart), and your extra fields (hidden,deleted,created_at,updated_at,...). So you have a specific content element of a certain block type, on a single page in a specific position... I guess that's what you wanted ;)

**Comment by ikkez** [comment]
hi @webbird. Could you solve the issue?

**Comment by webbird** [comment]
Sorry for being late, I am very busy with other things, so I am unable to work this out at the moment. But I'm sure you're right. ;) I close this as it can be re-opened if needed. Thank you for your help.
