### ISSUE TITLE
Fatal error: Call to a member function prepareFilter() on null

### ISSUE THREAD

**Issue by royhg** [ikkez/f3-cortex#47]
Hi Christian,

Its Exception generated
I used fatfree 3.6.0 and cortex 1.4.3..

Regards
Roy

**Comment by ikkez** [comment]
edge version of F3 3.6.x? because ` Declaration of DB\Cortex::count() ` is an issue with the newer F3 that changed the API slightly at this point, which is already fixed in the latest commits. 
Well `prepareFilter() on null` means that you work on a not-loaded mapper somewhere. Can't tell if that's an issue in the plugin or your code, without further details (stack trace?). Or maybe wait for tomorrow.

**Comment by ikkez** [comment]
were you able to solve the issue?

**Comment by royhg** [comment]
It already solved when using v1.5.0 release
