### ISSUE TITLE
SQLSTATE[HY000] [1203] Too many connection

### ISSUE THREAD

**Issue by aristadiki** [ikkez/f3-cortex#59]
Hi,

I used Fatfree 3.6 and cortex for relational database; 
I made Database::instance by extends Prefab to make the connection to mysql.
In my shared hosting it works fine.
But in other my dedicated server it got error SQLSTATE[HY000] [1203];
I've contact the provider, they said its too many connection over 1000. They asked to optimize the script.
Can you help me?

**Comment by ikkez** [comment]
How does you Database classes look like and why you extend Prefab? Sounds like you have opended such many connections. Usually you just make an instance of DB\SQL and save that to the F3 hive or put it into the Registry.

**Comment by ikkez** [comment]
okay and where & how do you use that? Everytime you call `Database::instance()->connect()` it will spawn a new DB connection. you probably want to put the connection initialisation into a `__construct` function and store the `$db` instance in a class property.. then just add a getter that returns the instance.. otherwise it would be pointless to use `Prefab` anyways.
