### ISSUE TITLE
Implement real cache of table schema

### ISSUE THREAD

**Issue by dmitrywicked** [ikkez/f3-cortex#68]
Hello!

Currently table schema "cache" done via static property
https://github.com/ikkez/f3-cortex/blob/master/lib/db/cortex.php#L228

while it also could be implemented using real cache as option , e.g. f3 CACHE
because in fact schema changes only happen when some update of the table structure happens, which is not often

and at the same time currently we have +1 more query on each ORM model initialization, which is expensive for high load systems and also could be reason of locking issue and poor performance due to db concurrency.

Please consider this idea, thank you.

**Comment by ikkez** [comment]
That "cache" is actually only for storing the initial state of the mapper schema. As the underlaying schema array is patched with the whitelist applied, it would lost track of existing fields otherwise. However, this method is not causing any additional queries, as `$this->mapper->schema();` is only returning an existing array. Caching the schema from table is done in the F3 mapper itself, and can be adjusted with the constructors `$ttl` attribute.
So not sure where your +1 query does come from.. Have you turned $fluid mode on? That can cause this issue.. turn it off when you re not expecting schema changes.

**Comment by dmitrywicked** [comment]
thank you for the reply, it all makes sense, sorry for not being attentive enough and taking your time. Indeed it is possible to control cache of the table schema through db mapper, my goal was to let schema cache persist forever and automatically clear it only on new deployments. I can see now that it's already achievable with current version of f3 and cortex.
