### ISSUE TITLE
Relation with a field which value can appears in several rows

### ISSUE THREAD

**Issue by Abzuu** [ikkez/f3-cortex#79]
Hello, i have a deep relationship between 3 SQL tables like this : 

t1->t2->t3

t1.fieldconf=[
'name' => ['type' => \DB\SQL\Schema::DT_VARCHAR128]
'section'=>['has-many'=>['t2','category']]
],

t2.fieldconf=[
'name' => ['type' => \DB\SQL\Schema::DT_VARCHAR128],
'category'=>['belongs-to-one'=>['t1','name']],
'articles'=>['has-many'=>['t3','section']]
]

t3.fieldconf=[
'name' => ['type' => \DB\SQL\Schema::DT_VARCHAR128],
'section'=>['belongs-to-one'=>['t2', 'name']],
]

My problem is that in t2, i can have several rows with the same 'name', and differenciated with the 'category'.

Imagine t2 have theses rows:
0 -> [name => 'nameA', category => 'categoryA], 
1 -> [name => 'nameB', category => 'categoryA], 
2 -> [name => 'nameC', category => 'categoryA], 
3 -> [name => 'nameA', category => 'categoryB]
So, 'nameA' exists twice, in two different 'category'.

And t3 theses rows:
0 -> [name => 'foo', section=> 'nameA', category => 'categoryA' ], 
1 -> [ name => 'foo2', section => 'nameA', category => 'categoryA' ],
2 -> [ name => 'foo3', section => 'nameA', category => 'categoryA' ],
3 ->  [ name => 'foo', section => 'nameA', category => 'categoryB' ]

Then, when i choose a 'category' (represented by the t1):
t1Mapper->load(array('name = ?', 'categoryA');
t1Mapper->cast(*some filters here*);

I have this kind of array:

t1.section=>[
  t2.articles=>[
      0 [ name => 'foo', section => 'nameA' ],
      1 [ name => 'foo2', section => 'nameA' ],
      2 [ name => 'foo3', section => 'nameA' ],
      3 [ name => 'foo', section => 'nameA' ]
  ],
  t2.articles=>[
      ...
  ],
  t2.articles=>[
      ...
  ],
]

What i want is to not have the 4th result in t2.articles, because in t3, the 4th row has 'categoryB', not 'categoryA'.
Is there a possibility to do that ? I think i miss a relation somewhere, but how to make it ? i don't think i can put a second 'belongs-to-one' with 'category' in the t3 ?

Thanks for your help :)

**Comment by ikkez** [comment]
You seem to get too many records because you link them by a non-unique name-value.
What's your relation field value for the sections? Do you put in 'nameA' or its `id`? Usually, when you just use the autoincremented primary key fields, you should have the records unique already. I read that articles belong to sections and sections belong to categories.. so t2.id=3 has category=2, and article is t3.section=3 ... and no category in t3 needed.
Then you'll have `$category->sections[]->articles[]` or `$article->section->category->name`.. etc. does that make sense? 🤔

**Comment by Abzuu** [comment]
I think i simply don't do as expected :)
I will rename my models for simplicity and to explain.

I have 3 tables : 'category', 'section', article', that i use to display things in my UI.
A category contain several sections, a section contain several articles.

Structure of 'CategoryModel':
-> name
-> parameter2
With fieldconf = [
'name' => ['type' => \DB\SQL\Schema::DT_VARCHAR128]
'section'=>['has-many'=>['SectionModel','category']]
]

Structure of 'SectionModel':
-> name
-> category
With fieldconf=[
'name' => ['type' => \DB\SQL\Schema::DT_VARCHAR128],
'category'=>['belongs-to-one'=>['CategoryModel','name']],
'articles'=>['has-many'=>['ArticleModel','section']]
]

Structure of 'ArticleModel':
-> name
-> section 
-> category
With fieldconf=[
'name' => ['type' => \DB\SQL\Schema::DT_VARCHAR128],
'section'=>['belongs-to-one'=>['SectionModel', 'name']],
]
The subtility here, is that two articles can have the same 'name'. And my relations are done at the setup of the table (i check if my tables are empty, and if empty (so my app have to be initialized), i do the setup and the initial insert of my values, from a preconfigured array).

So, when i retrieve all rows from my CategoryModel's Mapper (with a filter on only one category), i have my categories (OK), my sections (OK), but i have a problem with my articles, on those which have the same name, because the relation between 'Section' and 'Article', is on the name field. But in reality, in the 'ArticleModel', thoses rows are differentiated with the 'category' field (which I choose at the begining).

So i'm looking for a solution to have the articles, with:
-> the name of the section
-> and the category corresponding to the chosen category 

And finally i have all the articles with the name of the section. I am almost certain I'm not doing well, because i could simply bypass the issue doing several SQL request with filter i needs, instead of only one request, and there whould be no interest to the plugin :s

Thank you for your help and your time, because i believe i do a wrong use of the plugin..

**Comment by ikkez** [comment]
The problem is, that you're essentially want to link article and section, not by one field (foreign key) but two fields (article.section and article.category), which would be a compound key in sql, but this is not supported for relations in this plugin.. nevertheless, your database scheme doesnt seem to be normalized completely if you store the category field in the articles again.. you have those in your section table already!.. so the proper fix here would be to drop the category field from article, and use the proper IDs for the relations, so instead of:
in `SectionModel`:
```'category'=>['belongs-to-one'=>['CategoryModel','name']],```
use
```'category'=>['belongs-to-one'=>['CategoryModel','_id']],```
or simply `'category'=>['belongs-to-one'=>'CategoryModel'],`

and `ArticleModel`:
`'section'=>['belongs-to-one'=>['SectionModel', 'name']],` becomes:

`'section'=>['belongs-to-one'=>['SectionModel', '_id']],` or as shortcut: 
`'section'=>['belongs-to-one'=>'SectionModel'],`

In case you want to find articles by the name of a section, it's:
`$result = $article->has('section',['name = ?','SectionA'])->find();`
or by a category:
`$result = $article->has('section.category',['name = ?','Category1'])->find();`

and from a category as aggregation point:
```php
$category->load(['name = ?','Category1']);
foreach ($category->sections?:[] as $section) {
  foreach ($section->articles?:[] as $article) {
    $echo $article->name;
  }
}
```

or from a section as aggregation point:
```php
$section->has('category',['name = ?','Category1']);
$section->load(['name = ?','sectionA']);
$articles = $section->articles;
```

**Comment by Abzuu** [comment]
Thank you, it seems to be OK 💃 

I also had to make my relations "manually", ie in my ArticleModel, make the relation with two filters to identify the only one row i want a)the name of the section in SectionModel, and b) the  "_id" of the section in SectionModel which I fetch with the wanted category name in CategoryModel. I don't know if there is a simplier way, but it works :)

Thank you so much for your time and help, and also efforts to works with my example :)
